# docker-compose up
services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - C:\project\study\study_nestjs5\postgres-data:/var/lib/postgres/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
